---
Packaging:
  releaseVersion: <%= Skn::Version %>
  isTest: false
  isDevelopment: false
  isStaging: false
  isProduction: false
  configName: base
  short_name: skn

# Create a EnvStringHandler to support: SknSettings.env.development?
# Yes, its YAML trick
env: !ruby/string:SknUtils::EnvStringHandler <%= ENV['RACK_ENV'] %>

skn_base:
  secret: "37ae095d4e6ad226c79a03393f743d6c4f4f34f6123b9bef537beade8f364c36f9f7b10192ccd29c9ca4e75bff4207929304132849d0defc803a926406bb8876"

postgresql:
  url: postgres://localhost/SknServices_development
  user: postgres
  password: postgres

security:
  extra_digest_strength: 3
  session_expires: 480                # 8 hours
  remembered_for: 2160                # 32 hours
  verify_login_after_seconds: 14400   # 4 hours
  ! public_pages: # not easily stored in the xml, because of leading slash
   - /assets
   - /images
   - /fonts
   - /public
   - /sessions
   - /signout
   - /about
   - /contact
  user_cache:
    0: 'UserProfile Object'
