---
Packaging:
  releaseVersion: <%= Skn::Version %>
  isTest: false
  isDevelopment: false
  isStaging: false
  isProduction: false
  configName: base
  short_name: skn

# Create a EnvStringHandler to support: SknSettings.env.development?
# Yes, its YAML trick
env: !ruby/string:SknUtils::EnvStringHandler <%= ENV['RACK_ENV'] %>
app_root: <%=  File.expand_path(__dir__, '.').freeze %>

skn_base:
  secret: 37ae095d4e6ad226c79a03393f743d6c4d51b19fd8f6850e9ce5041312e631f6f9f7b10192ccd29c9ca4e75bff4207929304132849d0defc803a926406bbb676
  session_key: _skn_base_session
  session_domain: .skoona.net

postgresql:
  url: postgres://localhost/SknServices_development
  user: postgres
  password: postgres

security:
  extra_digest_strength: 3
  session_expires: 480                # 8 hours
  remembered_for: 2160                # 32 hours
  verify_login_after_seconds: 14400   # 4 hours

  profile_cache: !ruby/object:Concurrent::Map {backend: {0: UserProfiles Object}, write_lock: !ruby/object:Thread::Mutex {}, default_proc: nil }

  user_cache:
    0: UserProfile Objects

  ! public_pages:
    - /assets
    - /images
    - /fonts
    - /public
    - /sessions
    - /about
    - /contact

  ! asset_paths:
    - /assets
    - /images
    - /fonts
    - /public


